spring:
  datasource:
    url: jdbc:mariadb://173.199.119.240:3306/database
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
